//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonHandLeft
        {
            get
            {
                return SteamVR_Actions.default_SkeletonHandLeft;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonHandRight
        {
            get
            {
                return SteamVR_Actions.default_SkeletonHandRight;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerPull
        {
            get
            {
                return SteamVR_Actions.default_TriggerPull;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.default_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean AClick
        {
            get
            {
                return SteamVR_Actions.default_AClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean BClick
        {
            get
            {
                return SteamVR_Actions.default_BClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ThumbstickPos
        {
            get
            {
                return SteamVR_Actions.default_ThumbstickPos;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbstickClick
        {
            get
            {
                return SteamVR_Actions.default_ThumbstickClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean DPadRight
        {
            get
            {
                return SteamVR_Actions.default_DPadRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean DPadLeft
        {
            get
            {
                return SteamVR_Actions.default_DPadLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Single GripPull
        {
            get
            {
                return SteamVR_Actions.default_GripPull;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptics
        {
            get
            {
                return SteamVR_Actions.default_Haptics;
            }
        }
    }
}
